name: Frontend CD Simulation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Simulate Deployment
        run: echo "🚀 Frontend deployed successfully (simulation)"















# workflow: Frontend CD Simulation
        # Push code to GitHub
# ↓
# GitHub creates fresh Ubuntu VM
# ↓
# Download frontend code
# ↓
# Install Node.js
# ↓
# Install dependencies
# ↓
# Build React project (dist created)
# ↓
# Print success message
# ↓
# Destroy VM