name: Frontend CI

on:
  push:
    branches:
      - main      
          
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build








# 1. GitHub detects push to main
# 2. Create fresh Linux machine
# 3. Download your code
# 4. Install Node.js
# 5. Install dependencies
# 6. Build React app
# 7. If everything works → PASS ✅
# 8. If error → FAIL ❌


# pipeline working as follows:
# Start Job
# ↓
# Checkout Code
# ↓
# Setup Node
# ↓
# Install Dependencies
# ↓
# Build Project
# ↓
# Post steps (cleanup)
# ↓
# Complete Job
# ↓
# VM destroyed

